export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const START_DOWNLOAD_TASKS = "START_DOWNLOAD_TASKS";
export const DOWNLOAD_TASKS_SUCCESS = "DOWNLOAD_TASKS_SUCCESS";
export const DOWNLOAD_TASKS_ERROR = "START_DOWNLOAD_ERROR";

export const START_CHANGE_DONE = "START_CHANGE_DONE";
export const START_CHANGE_DONE_SUCCESS = "START_CHANGE_DONE_SUCCESS";
export const START_CHANGE_DONE_ERROR = "START_CHANGE_DONE_ERROR";

export const START_CHANGE_TODO = "START_CHANGE_TODO";
export const START_CHANGE_TODO_SUCCESS = "START_CHANGE_TODO_SUCCESS";
export const START_CHANGE_TODO_ERROR = "START_CHANGE_TODO_ERROR";
